# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_hastag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastag',
            name='user',
        ),
        migrations.DeleteModel(
            name='hastag',
        ),
    ]
